[package]
name = "shapeic-core"
version.workspace = true
edition.workspace = true
license.workspace = true
categories.workspace = true
rust-version.workspace = true
repository.workspace = true

[dev-dependencies]
shapeic-lut = { path = "../shapeic-lut" }
shapeic-mna = { path = "../shapeic-mna" }
symbolica = "2.1"
